name: xmonad-flothepo
synopsis: xmonad config
author: flothepo

dependencies:
  - X11
  - base
  - xmonad
  - xmonad-contrib
  - containers
  - libmpd

executables:
  xmonad:
    main: xmonad.hs
    source-dirs:
      - ./
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -fno-warn-missing-signatures
      - -threaded
      - -O2
      - -with-rtsopts=-N4
