#! /bin/sh

# Start some programs
sxhkd &
polybar example &
xfce4-power-manager &
# Set the window manager name to some nonsense like LG3D or compiz so that Intellij stuff works 
wmname compiz

# Set wallpaper
nitrogen --restore &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           6
# move windows with super + left mouse button
bspc config pointer_action1 move
# resize windows with super + middle mouse button
bspc config pointer_action2 resize_corner

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspwm config honor_size_hints true

bspc rule -a firefox desktop='^2' state=tiled focus=on
bspc rule -a firefox:Toolkit state=floating sticky=on
bspc rule -a Nm-connection-editor:nm-connection-editor state=floating
bspc rule -a Emacs desktop='^1' state=tiled
bspc rule -a matplotlib:matplotlib state=floating
